import Head from "next/head";
import React from "react";
import CardBase from "../components/ExampleComponent/CardBase";
import Backdrop from "../components/Utility/Backdrop";
import MainLayout from "../layout/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout
        facebook="#"
        instagram="#"
        whatsapp="#"
        contactEmail="atendimento@mapaculturaltaquara.com.br"
        contactNumber="(51)98910-5138"
        color="primary"
        metaDescription="Mapa cultural de Taquara"
        title="Mapa Cultural"
      >
        <div className="h-screen"></div>
      </MainLayout>
    </div>
  );
}
