import Head from "next/head";
import CardBase from "../components/ExampleComponent/CardBase";
import MainLayout from "../layout/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout
        metaDescription="Mapa cultural de Taquara"
        title="Mapa Cultural"
      ></MainLayout>
    </div>
  );
}
